### ISSUE TITLE
Automated Release To NuGet

### ISSUE THREAD

**Issue by Axemasta** [Axemasta/SuperWebView#4]
Currently the build pipeline releases to my internal feed and I manually upload to NuGet.org, update the pipelines so that I can release automatically

**Comment by Axemasta** [comment]
Also create a github release mirroring the info on here!

**Comment by AlexHedley** [comment]
```yml
name: Publish to NuGet

on:
  push:
    branches:
      - main # Your default release branch
    paths:
      - 'src/**'

jobs:
  publish:
    name: Publish to NuGet
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      
      - name: Publish
        uses: rohith/publish-nuget@v2
        #uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: src/VSSDK.Helpers.15.0/VSSDK.Helpers.15.0.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key
```
